// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WpfApp2.Models;

public partial class Animal
{
    public int ID { get; set; }

    public string name_pet { get; set; }

    public int specie_pet { get; set; }

    public virtual SpeciesAnimal specie_petNavigation { get; set; }
}