// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WpfApp2.Models;

public partial class DEB2Context : DbContext
{
    public DEB2Context()
    {
    }

    public DEB2Context(DbContextOptions<DEB2Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Animal> Animals { get; set; }

    public virtual DbSet<SpeciesAnimal> SpeciesAnimals { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer("Data Source=DESKTOP-QFRCAHK;" +
                "Initial Catalog=DEB2;" +
                "Integrated Security=True;" +
                "Trust Server Certificate=True;" +
				"Command Timeout=300;" +
				"MultipleActiveResultSets=True;");
        }
    }
        //=> optionsBuilder.UseSqlServer("Data Source=DESKTOP-QFRCAHK;Initial Catalog=DEB2;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Animal>(entity =>
        {
            entity.Property(e => e.name_pet)
                .IsRequired()
                .HasMaxLength(15);

            entity.HasOne(d => d.specie_petNavigation).WithMany(p => p.Animals)
                .HasForeignKey(d => d.specie_pet)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Animals_SpeciesAnimal");
        });

        modelBuilder.Entity<SpeciesAnimal>(entity =>
        {
            entity.ToTable("SpeciesAnimal");

            entity.Property(e => e.name_specie)
                .IsRequired()
                .HasMaxLength(10);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}