// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WpfApp2.Models;

public partial class SpeciesAnimal
{
    public int ID { get; set; }

    public string name_specie { get; set; }

    public virtual ICollection<Animal> Animals { get; set; } = new List<Animal>();
}